// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdfqshwqqsdjsicrrajl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkZnFzaHdxcXNkanNpY3JyYWpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxOTY2NTYsImV4cCI6MjA1MTc3MjY1Nn0.fX7p_mGT425y95CGNXEqnzTf_JUfYmOCLOMHaTTxzaE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);